service: eu-gas-detector

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
  deploymentBucket:
    name: serverless-deployment-gw
    serverSideEncryption: AES256
  environment:
    API_ID: ${env:API_ID}
    DYNANODB_TABLE: ${env:DYNAMODB_TABLE}
    SOURCE_EMAIL: ${env:SOURCE_EMAIL}
    RECIPIENT_EMAILS: ${env:RECIPIENT_EMAILS}
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_SECRET: ${env:TWITTER_ACCESS_SECRET}
    ASKTHEEU_EMAIL: ${env:ASKTHEEU_EMAIL}
    ASKTHEEU_PASSWORD: ${env:ASKTHEEU_PASSWORD}
    TWEET_TEMPLATE: >-
      Gas detected! A meeting between EU official {hosts_string_twitter} and gas company {guests_string_twitter} was scheduled for {date}.
 
      
      Just like big tobacco is banned from lobbying on health, we need #FossilFreePolitics to achieve #ClimateAction
    FOI_SUBJECT_TEMPLATE: "Access to documents request: {date} meeting between {hosts_string} and {guests_string}"
    FOI_BODY_TEMPLATE: >-
      Dear Sir or Madam,
      
      
      Referring to Regulation (EC) No 1049/2001 on public access to EU documents and to the 'Aarhus Convention' I would herewith like to ask for access to the following:
      
      
      All documents—including but not limited to correspondence, emails, minutes, notes (hand written or electronic), audio or video recordings, verbatim reports, operational conclusions, lines to take, briefings, and presentations—related to the meeting on {date} between {hosts_string} and {guests_string}.
      
      
      In consideration of the environment and the current circumstances with the COVID pandemic I would prefer to receive documents electronically.
      
      
      I would like to make clear I prefer you produce the documents on a rolling basis. At no point should the Commission's search for—or deliberations concerning—certain documents delay the production of others that the Commission has already retrieved and elected to produce.
      
      
      Should my request be denied wholly or partially, please explain the denial or all deletions referring to specific exemptions in the regulation. Also I would expect the partial release of documents in case of partial exemption according to article 4.6. I reserve the right to appeal.
      
      
      Please confirm having received this application. I look forward to your reply within 15 business days, according to the regulation.
      

      If anything is unclear or would benefit from further discussion please do not hesitate to contact me by email or on +44 7525 592 738. My address for any written correspondence necessary is Barnaby Pace, Global Witness, Rue Belliard 53, 1000, Bruxelles, Belgique.
      
      
      Thank you for your assistance.
      
      
      Yours sincerely
      
      Barnaby Pace 

functions:
  detector:
    handler: detector.lambda_handler
    timeout: 600
    events:
      - schedule: rate(1 day)
  actor:
    handler: actor.lambda_handler
    events:
      - http:
          method: get
          path: /

package:
  include:
   - data/**

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: non-linux
